import Head from 'next/head';
import Navigation from "@/components/out-app/static-components/Navigation";
import Footer from "@/components/out-app/static-components/Footer";

export default function DefaultLayout({ children }) {
  return (
    <>
      <Head>
        <title>Clikce-Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="body-wrapper">
        <Navigation/>
        <div className="main-content container">
          {children}
        </div>
        <Footer />
      </div>
    </>
  );
}
